# -*- coding: utf-8 -*-
"""advisory_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VYvJj8hV64pXa36-88RaCL7pQNaBcrSW

# Advisory Agent

## Part A -- Portfolio Advisory Agent (Agentic Think-Act-Observe Pattern)
"""

import os
import math

STOCK_UNIVERSE = {
    "PAYFIN":  {"beta": 1.35, "analyst_expected_return": 0.16, "std_dev": 0.28},
    "PAYRETAIL": {"beta": 0.85, "analyst_expected_return": 0.11, "std_dev": 0.17},
    "PAYINFRA": {"beta": 1.10, "analyst_expected_return": 0.135, "std_dev": 0.22},
    "PAYGOLD": {"beta": 0.20, "analyst_expected_return": 0.08, "std_dev": 0.12},
    "PAYBOND": {"beta": 0.05, "analyst_expected_return": 0.065, "std_dev": 0.04},
    "PAYTECH": {"beta": 1.55, "analyst_expected_return": 0.19, "std_dev": 0.34},
}
RISK_FREE_RATE = 0.07
MARKET_RETURN = 0.13

INVESTOR_PROFILES = [
    {"investor_id": "INV01", "risk_tolerance": "Conservative", "horizon_years": 3, "investment_amount_inr": 200000},
    {"investor_id": "INV02", "risk_tolerance": "Moderate", "horizon_years": 7, "investment_amount_inr": 500000},
    {"investor_id": "INV03", "risk_tolerance": "Aggressive", "horizon_years": 12, "investment_amount_inr": 300000},
    {"investor_id": "INV04", "risk_tolerance": "Moderate", "horizon_years": 5, "investment_amount_inr": 800000},
    {"investor_id": "INV05", "risk_tolerance": "Aggressive", "horizon_years": 2, "investment_amount_inr": 150000},
]

# Prescribed, required lookup table -- not a free-choice mapping.
ALLOCATION_TABLE = {
    "Conservative": ["PAYBOND", "PAYGOLD", "PAYRETAIL"],
    "Moderate": ["PAYRETAIL", "PAYINFRA", "PAYGOLD"],
    "Aggressive": ["PAYTECH", "PAYFIN", "PAYINFRA"],
}

PAIRWISE_CORRELATION = 0.3
ESCALATION_STD_THRESHOLD = 0.20

# Simulated external "tool call": looks up data from the local Call
def get_stock_data(ticker: str) -> dict:
    """Tool call: fetch beta / analyst_expected_return / std_dev for a ticker."""
    if ticker not in STOCK_UNIVERSE:
        raise KeyError(f"Unknown ticker: {ticker}")
    return dict(STOCK_UNIVERSE[ticker])


def capm_expected_return(beta: float) -> float:

    return RISK_FREE_RATE + beta * (MARKET_RETURN - RISK_FREE_RATE)


def portfolio_variance(weights: list, std_devs: list, rho: float = PAIRWISE_CORRELATION) -> float:

    n = len(weights)
    variance = 0.0
    for i in range(n):
        variance += (weights[i] ** 2) * (std_devs[i] ** 2)
    for i in range(n):
        for j in range(i + 1, n):
            cov_ij = rho * std_devs[i] * std_devs[j]
            variance += 2 * weights[i] * weights[j] * cov_ij
    return variance



# Narrative sentence -- the ONLY part gated by MOCK_LLM.

def build_narrative(investor_id, risk_tolerance, tickers, expected_return, volatility) -> str:
    mock_llm = os.environ.get("MOCK_LLM", "1")
    if mock_llm == "1" or mock_llm == "" or mock_llm is None:
        # Mock mode (graded baseline): deterministic f-string template.
        return (
            f"For {risk_tolerance} investor {investor_id}, we recommend an allocation "
            f"across {tickers} with an expected portfolio return of {expected_return:.1%} "
            f"and volatility of {volatility:.1%}."
        )
    else:

        return (
            f"[LLM mode -- no live LLM call wired up in this environment] "
            f"For {risk_tolerance} investor {investor_id}, we recommend an allocation "
            f"across {tickers} with an expected portfolio return of {expected_return:.1%} "
            f"and volatility of {volatility:.1%}."
        )


def run_agent_for_investor(investor: dict) -> dict:


    investor_id = investor["investor_id"]
    risk_tolerance = investor["risk_tolerance"]

    # ---------------- THINK ----------------

    tickers = ALLOCATION_TABLE[risk_tolerance]
    weights = [1 / 3, 1 / 3, 1 / 3]

    # ---------------- ACT (tool call) ----------------
    stock_data = {ticker: get_stock_data(ticker) for ticker in tickers}

    # ---------------- OBSERVE -> DECIDE ----------------
    per_stock_returns = [capm_expected_return(stock_data[t]["beta"]) for t in tickers]
    portfolio_expected_return = sum(w * r for w, r in zip(weights, per_stock_returns))

    std_devs = [stock_data[t]["std_dev"] for t in tickers]
    variance = portfolio_variance(weights, std_devs, PAIRWISE_CORRELATION)
    portfolio_std_dev = math.sqrt(variance)

    escalated = portfolio_std_dev > ESCALATION_STD_THRESHOLD

    result = {
        "investor_id": investor_id,
        "risk_tolerance": risk_tolerance,
        "tickers": tickers,
        "weights": weights,
        "per_stock_expected_returns": dict(zip(tickers, per_stock_returns)),
        "portfolio_expected_return": portfolio_expected_return,
        "portfolio_variance": variance,
        "portfolio_std_dev": portfolio_std_dev,
        "escalated": escalated,
    }

    if escalated:
        # Human-in-the-loop escalation: do not auto-finalize.
        result["status"] = "ESCALATED_TO_HUMAN_ADVISOR"
        result["narrative"] = None
    else:
        result["status"] = "FINALIZED"
        result["narrative"] = build_narrative(
            investor_id, risk_tolerance, tickers, portfolio_expected_return, portfolio_std_dev
        )

    return result


def run_all_investors() -> list:
    return [run_agent_for_investor(inv) for inv in INVESTOR_PROFILES]

"""## Run"""

results = run_all_investors()
for r in results:
    print("=" * 70)
    print(f"Investor: {r['investor_id']} ({r['risk_tolerance']})")
    print(f"Allocation: {r['tickers']} ")
    print(f"Portfolio expected return (CAPM): {r['portfolio_expected_return']:.4%}")
    print(f"Portfolio std dev: {r['portfolio_std_dev']:.4%}")
    print(f"Status: {r['status']}")
    if r["status"] == "ESCALATED_TO_HUMAN_ADVISOR":
        print("  -> ESCALATED_TO_HUMAN_ADVISOR: std dev exceeds 20% threshold.")
        print(f"     Computed numbers attached: return={r['portfolio_expected_return']:.4%}, "
              f"std_dev={r['portfolio_std_dev']:.4%}")
    else:
        print(f"Narrative: {r['narrative']}")