# -*- coding: utf-8 -*-
"""dcf_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAmOj4vbA9RW6zqi7amsTgt9jVQPVSbo

# DCF Calculator

## Part D - DCF Valuation Calculator for a Hypothetical Paytm Business Line.
"""

import math

STOCK_UNIVERSE = {
    "PAYFIN":  {"beta": 1.35, "analyst_expected_return": 0.16, "std_dev": 0.28},
    "PAYRETAIL": {"beta": 0.85, "analyst_expected_return": 0.11, "std_dev": 0.17},
    "PAYINFRA": {"beta": 1.10, "analyst_expected_return": 0.135, "std_dev": 0.22},
    "PAYGOLD": {"beta": 0.20, "analyst_expected_return": 0.08, "std_dev": 0.12},
    "PAYBOND": {"beta": 0.05, "analyst_expected_return": 0.065, "std_dev": 0.04},
    "PAYTECH": {"beta": 1.55, "analyst_expected_return": 0.19, "std_dev": 0.34},
}
RISK_FREE_RATE = 0.07
MARKET_RETURN = 0.13

# Stated inputs (illustrative, chosen for this exercise)

# Base-year (Year 0, i.e. most recent actual year) operating figures, INR

BASE_EBIT = 500_000_000           # INR 50 crore (500,000,000)
TAX_RATE = 0.25                   # 25% illustrative effective tax rate
BASE_DA = 80_000_000              # INR 8 crore -- Depreciation & amortization
BASE_CAPEX = 120_000_000          # INR 12 crore -- Capital expenditure
BASE_DELTA_NWC = 30_000_000       # INR 3 crore -- Increase in net working capital


GROWTH_RATES_5YR = [0.18, 0.15, 0.12, 0.09, 0.06]   # Year 1 .. Year 5
TERMINAL_GROWTH_RATE = 0.04                          # g, in perpetuity

# Cost of equity: CAPM using a STOCK_UNIVERSE beta

COST_OF_EQUITY_BETA_TICKER = "PAYFIN"
COST_OF_EQUITY = RISK_FREE_RATE + STOCK_UNIVERSE[COST_OF_EQUITY_BETA_TICKER]["beta"] * (
    MARKET_RETURN - RISK_FREE_RATE
)

# Cost of debt: illustrative pre-tax cost of debt, tax-shielded.
PRE_TAX_COST_OF_DEBT = 0.08
AFTER_TAX_COST_OF_DEBT = PRE_TAX_COST_OF_DEBT * (1 - TAX_RATE)

# Illustrative capital structure split.
WEIGHT_EQUITY = 0.70
WEIGHT_DEBT = 0.30

WACC = WEIGHT_EQUITY * COST_OF_EQUITY + WEIGHT_DEBT * AFTER_TAX_COST_OF_DEBT

# EV/EBITDA cross-check inputs (illustrative)
CROSS_CHECK_EBITDA = BASE_EBIT + BASE_DA   # EBITDA = EBIT + D&A
CROSS_CHECK_MULTIPLE = 9.0                 # illustrative fintech-lending multiple

def compute_base_fcff() -> float:
    return BASE_EBIT * (1 - TAX_RATE) + BASE_DA - BASE_CAPEX - BASE_DELTA_NWC


def project_fcff(base_fcff: float, growth_rates: list) -> list:
    fcffs = []
    current = base_fcff
    for g in growth_rates:
        current = current * (1 + g)
        fcffs.append(current)
    return fcffs


def terminal_value(final_year_fcff: float, wacc: float, terminal_growth: float) -> float:
    """Gordon growth / growing-perpetuity formula, valued at the end of Year 5."""
    return final_year_fcff * (1 + terminal_growth) / (wacc - terminal_growth)


def discount_to_pv(cashflows_by_year: list, wacc: float) -> list:
    """cashflows_by_year is a list of (year, cashflow) tuples."""
    return [(year, cf, cf / ((1 + wacc) ** year)) for year, cf in cashflows_by_year]


def run_dcf(wacc: float = WACC, terminal_growth: float = TERMINAL_GROWTH_RATE) -> dict:
    base_fcff = compute_base_fcff()
    projected_fcff = project_fcff(base_fcff, GROWTH_RATES_5YR)

    pv_rows = discount_to_pv(list(enumerate(projected_fcff, start=1)), wacc)
    pv_of_explicit_fcff = sum(pv for _, _, pv in pv_rows)

    tv_year5 = terminal_value(projected_fcff[-1], wacc, terminal_growth)
    pv_of_terminal_value = tv_year5 / ((1 + wacc) ** 5)

    enterprise_value = pv_of_explicit_fcff + pv_of_terminal_value

    return {
        "wacc": wacc,
        "terminal_growth": terminal_growth,
        "base_fcff": base_fcff,
        "projected_fcff": projected_fcff,
        "pv_rows": pv_rows,
        "pv_of_explicit_fcff": pv_of_explicit_fcff,
        "terminal_value_year5": tv_year5,
        "pv_of_terminal_value": pv_of_terminal_value,
        "enterprise_value": enterprise_value,
    }


def sensitivity_table(base_wacc: float = WACC, base_growth: float = TERMINAL_GROWTH_RATE) -> dict:
    """3x3 grid varying WACC and terminal growth by +/-1 percentage point each."""
    wacc_values = [base_wacc - 0.01, base_wacc, base_wacc + 0.01]
    growth_values = [base_growth - 0.01, base_growth, base_growth + 0.01]

    grid = {}
    worst_case_margin = None
    for w in wacc_values:
        for g in growth_values:
            ev = run_dcf(wacc=w, terminal_growth=g)["enterprise_value"]
            grid[(round(w, 4), round(g, 4))] = ev
            margin = w - g
            if worst_case_margin is None or margin < worst_case_margin:
                worst_case_margin = margin

    return {
        "wacc_values": wacc_values,
        "growth_values": growth_values,
        "grid": grid,
        "worst_case_wacc_minus_growth_margin": worst_case_margin,
    }


def ev_ebitda_cross_check(ebitda: float = CROSS_CHECK_EBITDA, multiple: float = CROSS_CHECK_MULTIPLE) -> float:
    return ebitda * multiple

print("=" * 70)
print("INPUTS (stated assumptions)")
print("=" * 70)
print(f"Base EBIT:                 INR {BASE_EBIT:,.0f}")
print(f"Tax rate:                  {TAX_RATE:.0%}")
print(f"D&A:                       INR {BASE_DA:,.0f}")
print(f"CapEx:                     INR {BASE_CAPEX:,.0f}")
print(f"Delta NWC:                 INR {BASE_DELTA_NWC:,.0f}")
print(f"5yr growth rates:          {[f'{g:.0%}' for g in GROWTH_RATES_5YR]}")
print(f"Terminal growth rate:      {TERMINAL_GROWTH_RATE:.2%}")
print(f"Cost of equity (CAPM, beta={STOCK_UNIVERSE[COST_OF_EQUITY_BETA_TICKER]['beta']}, {COST_OF_EQUITY_BETA_TICKER}): {COST_OF_EQUITY:.2%}")
print(f"After-tax cost of debt:    {AFTER_TAX_COST_OF_DEBT:.2%} (pre-tax {PRE_TAX_COST_OF_DEBT:.2%})")
print(f"Capital structure:         {WEIGHT_EQUITY:.0%} equity / {WEIGHT_DEBT:.0%} debt")
print(f"WACC:                      {WACC:.2%}")
print(f"WACC - terminal growth:    {WACC - TERMINAL_GROWTH_RATE:.2%} (must be >= 3pp)")

print()
print("=" * 70)
print("BASE-CASE DCF")
print("=" * 70)
base = run_dcf()
print(f"Base-year FCFF:            INR {base['base_fcff']:,.0f}")
for year, cf, pv in base["pv_rows"]:
    print(f"  Year {year}: FCFF = INR {cf:,.0f}   PV = INR {pv:,.0f}")
print(f"PV of explicit FCFF (Yr1-5): INR {base['pv_of_explicit_fcff']:,.0f}")
print(f"Terminal value (end Yr5):   INR {base['terminal_value_year5']:,.0f}")
print(f"PV of terminal value:       INR {base['pv_of_terminal_value']:,.0f}")
print(f"Enterprise value (DCF):     INR {base['enterprise_value']:,.0f}")

print()
print("=" * 70)
print("SENSITIVITY TABLE (3x3 grid, +/-1pp on WACC and terminal growth)")
print("=" * 70)
sens = sensitivity_table()
header = "WACC \\ g".ljust(12) + "".join(f"{g:.1%}".rjust(16) for g in sens["growth_values"])
print(header)
for w in sens["wacc_values"]:
    row = f"{w:.2%}".ljust(12)
    for g in sens["growth_values"]:
        ev = sens["grid"][(round(w, 4), round(g, 4))]
        row += f"{ev:,.0f}".rjust(16)
    print(row)
print()
print(f"Worst-case (min) WACC - terminal growth margin across the 9 cells: "
      f"{sens['worst_case_wacc_minus_growth_margin']:.2%}")
assert sens["worst_case_wacc_minus_growth_margin"] >= 0.01, (
    "Self-check failed: WACC must exceed terminal growth by >= 1pp in every grid cell."
)
print("Self-check PASSED: WACC exceeds terminal growth by >= 1pp in every one of the 9 cells.")

print()
print("=" * 70)
print("EV/EBITDA CROSS-CHECK")
print("=" * 70)
ev_multiple_based = ev_ebitda_cross_check()
print(f"Illustrative EBITDA (EBIT + D&A): INR {CROSS_CHECK_EBITDA:,.0f}")
print(f"Illustrative multiple:            {CROSS_CHECK_MULTIPLE}x")
print(f"EV/EBITDA-implied enterprise value: INR {ev_multiple_based:,.0f}")
print(f"DCF-implied enterprise value:       INR {base['enterprise_value']:,.0f}")
diff_pct = (base["enterprise_value"] - ev_multiple_based) / ev_multiple_based
print(f"Difference (DCF vs multiple):       {diff_pct:+.1%}")
print()
print("The DCF and EV/EBITDA estimates are broadly aligned, providing a useful sanity check despite using different methods."
      "Any gap mainly reflects the DCF's explicit growth and terminal assumptions versus the market-based peer valuation embedded in the multiple approach.")











