# -*- coding: utf-8 -*-
"""debate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zo-SsDXqi6kXk7iQHhRrF4om1q-L1JtB

# Debate

Part C -- Multi-Agent Debate Demo (Bull / Bear / Synthesizer).
"""

STOCK_UNIVERSE = {
    "PAYFIN":  {"beta": 1.35, "analyst_expected_return": 0.16, "std_dev": 0.28},
    "PAYRETAIL": {"beta": 0.85, "analyst_expected_return": 0.11, "std_dev": 0.17},
    "PAYINFRA": {"beta": 1.10, "analyst_expected_return": 0.135, "std_dev": 0.22},
    "PAYGOLD": {"beta": 0.20, "analyst_expected_return": 0.08, "std_dev": 0.12},
    "PAYBOND": {"beta": 0.05, "analyst_expected_return": 0.065, "std_dev": 0.04},
    "PAYTECH": {"beta": 1.55, "analyst_expected_return": 0.19, "std_dev": 0.34},
}
RISK_FREE_RATE = 0.07
MARKET_RETURN = 0.13


# Ticker chosen for this debate demo.
DEBATE_TICKER = "PAYTECH"

# Bull Argument

def bull_argument(ticker: str) -> str:
    data = STOCK_UNIVERSE[ticker]
    r = data["analyst_expected_return"]
    b = data["beta"]
    return (
        f"Bull case for {ticker}: with an expected return of {r:.1%} against a beta of "
        f"{b:.2f}, this offers attractive risk-adjusted upside for investors willing to "
        f"take on above-market volatility."
    )

# Bear Argument

def bear_argument(ticker: str) -> str:
    data = STOCK_UNIVERSE[ticker]
    sd = data["std_dev"]
    b = data["beta"]
    return (
        f"Bear case for {ticker}: a standard deviation of {sd:.1%} combined with a beta "
        f"of {b:.2f} means this stock swings well beyond the market, and that volatility "
        f"can erase gains just as quickly as it creates them."
    )

# Synthesizer Summary

def synthesizer_summary(ticker: str, bull_text: str, bear_text: str) -> str:
    data = STOCK_UNIVERSE[ticker]
    r = data["analyst_expected_return"]
    sd = data["std_dev"]
    return (
        f"On balance, {ticker} pairs a relatively high expected return of {r:.1%} with "
        f"relatively high volatility ({sd:.1%} std dev), so the bull's upside case and the "
        f"bear's risk case are really two sides of the same coin. It suits investors with "
        f"a longer horizon and a genuine tolerance for drawdowns, but is a poor fit for "
        f"anyone prioritizing capital preservation."
    )

# Run the Debate

def run_debate(ticker: str = DEBATE_TICKER) -> dict:
    bull = bull_argument(ticker)
    bear = bear_argument(ticker)
    synthesis = synthesizer_summary(ticker, bull, bear)
    return {"ticker": ticker, "bull": bull, "bear": bear, "synthesis": synthesis}

result = run_debate()
print("=" * 70)
print(f"Debate ticker: {result['ticker']}")
print("-" * 70)
print(f"BULL:\n{result['bull']}\n")
print(f"BEAR:\n{result['bear']}\n")
print(f"SYNTHESIZER:\n{result['synthesis']}")