# -*- coding: utf-8 -*-
"""extract_disclosure.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWKhZqsB_Lb6Fm5UGOpeRl08hwuXvJf7

# Extract Disclosure

## Part B -- Structured Disclosure Extraction.
"""

import re

DISCLOSURE_SNIPPETS = [
    "doc_01: Assuming input costs remain stable through the next two quarters, we expect "
    "margins to hold at current levels.",
    "doc_02: The company faces an ongoing litigation matter related to a former vendor "
    "contract; management believes the exposure is not material.",
    "doc_03: Our top three customers together account for approximately 42 percent of "
    "total revenue this year.",
    "doc_04: We remain cautiously optimistic about demand recovery, though visibility "
    "beyond the next quarter is limited given macro uncertainty.",
    "doc_05: The board is confident in the long-term strategy and has approved an "
    "expanded capital expenditure plan for the coming year.",
    "doc_06: A recent regulatory notice has been received regarding data-localization "
    "compliance; the company is in active dialogue with the regulator.",
]

RISK_FLAG_PATTERNS = {
    "litigation": re.compile(r"\blitigation\b", re.IGNORECASE),
    "regulatory": re.compile(r"\bregulatory\b", re.IGNORECASE),
    "customer_concentration": re.compile(
        r"(top\s+\w+\s+customers|customer\s+concentration|percent\s+of\s+total\s+revenue)",
        re.IGNORECASE,
    ),
}

HEDGING_PATTERNS = [
    re.compile(r"\bassuming\b", re.IGNORECASE),
    re.compile(r"\bcautiously\b", re.IGNORECASE),
    re.compile(r"\bvisibility\b", re.IGNORECASE),
]

CONFIDENT_PATTERNS = [
    re.compile(r"\bconfident\b", re.IGNORECASE),
    re.compile(r"\bapproved\b", re.IGNORECASE),
]

def extract_signals(snippet: str) -> dict:
    """Rule-based (mock) structured extraction from a disclosure snippet.

    Returns:
        {"risk_flags": [...], "hedging_detected": bool,
         "sentiment": "confident"|"cautious"|"neutral"}
    """
    risk_flags = [name for name, pattern in RISK_FLAG_PATTERNS.items() if pattern.search(snippet)]
    hedging_detected = any(pattern.search(snippet) for pattern in HEDGING_PATTERNS)

    if any(pattern.search(snippet) for pattern in CONFIDENT_PATTERNS):
        sentiment = "confident"
    elif hedging_detected:
        sentiment = "cautious"
    else:
        sentiment = "neutral"

    return {
        "risk_flags": risk_flags,
        "hedging_detected": hedging_detected,
        "sentiment": sentiment,
    }

def run_all_snippets() -> list:
    results = []
    for snippet in DISCLOSURE_SNIPPETS:
        doc_id = snippet.split(":", 1)[0].strip()
        results.append({"doc_id": doc_id, "text": snippet, **extract_signals(snippet)})
    return results

"""### RUN"""

for r in run_all_snippets():
    print("=" * 70)
    print(f"{r['doc_id']}")
    print(f"  risk_flags:       {r['risk_flags']}")
    print(f"  hedging_detected: {r['hedging_detected']}")
    print(f"  sentiment:        {r['sentiment']}")